---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-uploads
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hdd
  resources:
    requests:
      storage: 500Gi
