apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../manifests/namespace.yaml
  - ../../manifests/flask-backend/deployment.yaml
  - ../../manifests/flask-backend/service.yaml
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: nest
