apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nest

resources:
  - 00-namespace.yaml
  - 10-configmap.yaml
  - 11-secrets.yaml
  - 20-postgres-pvc.yaml
  - 20-postgres-statefulset.yaml
  - 21-postgres-service.yaml
  - 30-redis-pvc.yaml
  - 30-redis-deployment.yaml
  - 31-redis-service.yaml
  - 40-app-deployment.yaml
  - 41-app-service.yaml
  - 50-ingress.yaml
  - 60-servicemonitor.yaml

labels:
  - pairs:
      managed-by: kustomize
