apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nest-alpha
namePrefix: alpha-
commonLabels:
  environment: alpha
resources:
  - ../../base
replicas:
  - name: flask-backend
    count: 1
images:
  - name: registry-dal2.penguintech.io/nest/flask-backend
    newTag: latest
configMapGenerator:
  - name: nest-config
    behavior: merge
    literals:
      - LOG_LEVEL=DEBUG
      - RELEASE_MODE=false
