---
apiVersion: v1
kind: Service
metadata:
  name: nest-app
  namespace: nest-dev
  labels:
    app: nest
    component: application
spec:
  type: ClusterIP
  selector:
    app: nest
    component: application
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http

---
apiVersion: v1
kind: Service
metadata:
  name: nest-app
  namespace: nest-staging
  labels:
    app: nest
    component: application
spec:
  type: ClusterIP
  selector:
    app: nest
    component: application
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http

---
apiVersion: v1
kind: Service
metadata:
  name: nest-app
  namespace: nest-prod
  labels:
    app: nest
    component: application
spec:
  type: ClusterIP
  selector:
    app: nest
    component: application
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
