{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nest.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nest.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "nest.selectorLabels" . | nindent 6 }}
  {{- if .Values.networkPolicy.policyTypes }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  {{- end }}
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
  {{- end }}
{{- end }}
