apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nest-beta
namePrefix: beta-
commonLabels:
  environment: beta
resources:
  - ../../base
replicas:
  - name: flask-backend
    count: 2
images:
  - name: registry-dal2.penguintech.io/nest/flask-backend
    newTag: latest
configMapGenerator:
  - name: nest-config
    behavior: merge
    literals:
      - LOG_LEVEL=INFO
      - RELEASE_MODE=false
